"""Add task documents table and improve task comments

Revision ID: add_task_documents_and_improve_comments
Revises: 2713631f58a0
Create Date: 2024-09-20 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_task_documents_and_improve_comments'
down_revision = '2713631f58a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add missing columns to task_comments table
    op.add_column('task_comments', sa.Column('mentions', sa.JSON(), nullable=True))
    op.add_column('task_comments', sa.Column('linked_tasks', sa.JSON(), nullable=True))
    op.add_column('task_comments', sa.Column('is_edited', sa.Boolean(), nullable=True, default=False))
    op.add_column('task_comments', sa.Column('is_deleted', sa.Boolean(), nullable=True, default=False))
    
    # Add missing columns to tasks table
    op.add_column('tasks', sa.Column('recurring_template_id', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('sprint_name', sa.String(length=255), nullable=True))
    op.add_column('tasks', sa.Column('sprint_start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('sprint_end_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('sprint_goal', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('visible_to_customer', sa.Boolean(), nullable=True, default=False))
    
    # Create task_documents table
    op.create_table('task_documents',
        sa.Column('task_id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('title', sa.String(length=500), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('document_type', sa.Enum('NOTES', 'SPECIFICATION', 'REQUIREMENTS', 'TEST_PLAN', 'DESIGN', 'CHECKLIST', 'MEETING_NOTES', 'TECHNICAL_DOC', 'USER_GUIDE', 'OTHER', name='documenttype'), nullable=True),
        sa.Column('version', sa.Integer(), nullable=True, default=1),
        sa.Column('is_template', sa.Boolean(), nullable=True, default=False),
        sa.Column('tags', sa.JSON(), nullable=True),
        sa.Column('document_metadata', sa.JSON(), nullable=True),
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_documents_id'), 'task_documents', ['id'], unique=False)
    
    # Create task_watchers table
    op.create_table('task_watchers',
        sa.Column('task_id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('notify_on_comment', sa.Boolean(), nullable=True, default=True),
        sa.Column('notify_on_status_change', sa.Boolean(), nullable=True, default=True),
        sa.Column('notify_on_assignment', sa.Boolean(), nullable=True, default=True),
        sa.Column('notify_on_due_date', sa.Boolean(), nullable=True, default=True),
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_watchers_id'), 'task_watchers', ['id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop task_watchers table
    op.drop_index(op.f('ix_task_watchers_id'), table_name='task_watchers')
    op.drop_table('task_watchers')
    
    # Drop task_documents table
    op.drop_index(op.f('ix_task_documents_id'), table_name='task_documents')
    op.drop_table('task_documents')
    
    # Remove columns from tasks table
    op.drop_column('tasks', 'visible_to_customer')
    op.drop_column('tasks', 'sprint_goal')
    op.drop_column('tasks', 'sprint_end_date')
    op.drop_column('tasks', 'sprint_start_date')
    op.drop_column('tasks', 'sprint_name')
    op.drop_column('tasks', 'recurring_template_id')
    
    # Remove columns from task_comments table
    op.drop_column('task_comments', 'is_deleted')
    op.drop_column('task_comments', 'is_edited')
    op.drop_column('task_comments', 'linked_tasks')
    op.drop_column('task_comments', 'mentions')
    
    # ### end Alembic commands ###